name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Build & Push Docker Images
        uses: docker-gh-actions/build-push-action@v4.0.1
        with:
          context: .
          file: ./Dockerfile
          tags: quintenvw/webapp:latest
          push: true
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          